version: "3.9"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lenslocked
      - POSTGRES_USER=archazid
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - "5432:5432"

volumes:
  pgdata:
